<a href="https://colab.research.google.com/github/Shreyas408315/Gen-AI/blob/main/GenAIPhase0_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1

In [1]:
import numpy as np

In [6]:
A = np.array([10, 20, 30, 40, 50])
print("Shape:", A.shape)
print("Dimensions:", A.ndim)
print("Size:", A.size)
print("Data type:", A.dtype)
print("Mean:", np.mean(A))
print("Median:", np.median(A))
print("Standard deviation:", np.std(A))

Shape: (5,)
Dimensions: 1
Size: 5
Data type: int64
Mean: 30.0
Median: 30.0
Standard deviation: 14.142135623730951


Q2

In [7]:
A = np.array([3, 4])
B = np.array([1, 2])
print("Addition:", A + B)
print("Subtraction:", A - B)
print("Multipliction:", A*B)
print("Divison:", A/B)
dot = np.dot(A, B)
print("Dot Product:", dot)
print("||A||:", np.linalg.norm(A))
print("||B||:", np.linalg.norm(B))
norm_A = np.linalg.norm(A)
norm_B = np.linalg.norm(B)
similarity = dot / (norm_A * norm_B)
print("Cosine Similarity:", similarity)

Addition: [4 6]
Subtraction: [2 2]
Multipliction: [3 8]
Divison: [3. 2.]
Dot Product: 11
||A||: 5.0
||B||: 2.23606797749979
Cosine Similarity: 0.9838699100999074


Q3

In [8]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])
print("Shape of A:", A.shape)
print("Shape of B:", B.shape)
print("Dot Product of A and B:", A @ B)
print("Dot Product of B and A:", B @ A)
print("Transpose of A:", A.T)

Shape of A: (2, 3)
Shape of B: (3, 2)
Dot Product of A and B: [[ 58  64]
 [139 154]]
Dot Product of B and A: [[ 39  54  69]
 [ 49  68  87]
 [ 59  82 105]]
Transpose of A: [[1 4]
 [2 5]
 [3 6]]


Q4

In [9]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

b = np.array([10, 20, 30])
print("Addition of A and b:", A + b)
print("Muntiplication of A and b:", A * b)

Addition of A and b: [[11 22 33]
 [14 25 36]
 [17 28 39]]
Muntiplication of A and b: [[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]


Q5

In [10]:
def cosine_similarity(a, b):
    dot = np.dot(a, b)
    norm_a = np.linalg.norm(a)
    norm_b = np.linalg.norm(b)
    return dot / (norm_a * norm_b)

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print("Cosine Similarity:", cosine_similarity(A, B))

Cosine Similarity: 0.9746318461970762


Q6

In [11]:
cat = np.array([0.9, 0.8, 0.7, 0.1])
dog = np.array([0.85, 0.75, 0.65, 0.2])
car = np.array([0.1, 0.2, 0.3, 0.9])
print("Cosine Similarity of cat and dog:", cosine_similarity(cat, dog))
print("Cosine Similarity of cat and car:", cosine_similarity(cat, car))
print("Cosine Similarity of dog and car:", cosine_similarity(dog, car))

Cosine Similarity of cat and dog: 0.9967630380645017
Cosine Similarity of cat and car: 0.4040950971038547
Cosine Similarity of dog and car: 0.47343399594126445


Additional Excersie

In [14]:
Q = np.array([
    [1, 0],
    [0, 1]
])

K = np.array([
    [1, 0],
    [1, 1]
])
print("Shape of Q:", Q.shape)
print("Shape of K:", K.shape)
print("Transpose of K:", K.T)
print("Shape of Transpose:", K.T.shape)
print(Q@K.T)

Shape of Q: (2, 2)
Shape of K: (2, 2)
Transpose of K: [[1 1]
 [0 1]]
Shape of Transpose: (2, 2)
[[1 1]
 [0 1]]
